spring.application.name=file-service
spring.datasource.url=jdbc:postgresql://localhost:5432/files_db
spring.datasource.username=postgres
spring.datasource.password=Abhi123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
aws.s3.bucket=file-service-abhishek
